
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class parserUSym {
  /* terminals */
  public static final int DosPuntos = 9;
  public static final int Color = 8;
  public static final int Usuario = 6;
  public static final int Llave_Cierra = 3;
  public static final int EOF = 0;
  public static final int Numeros = 7;
  public static final int Coma = 4;
  public static final int Llave_Abre = 2;
  public static final int error = 1;
  public static final int Punto_Coma = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Llave_Abre",
  "Llave_Cierra",
  "Coma",
  "Punto_Coma",
  "Usuario",
  "Numeros",
  "Color",
  "DosPuntos"
  };
}

